# -*- coding: utf-8 -*-
"""End-to-End .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k86R_Zc0jbqkBo4UoWfHu79lnwegHfo_

For installing the Libraries that we need:
"""

pip install pandas numpy scikit-learn xgboost matplotlib seaborn

"""For loading the our dataset:"""

import pandas as pd
df = pd.read_csv("/content/sample_data/train.csv")
print(df.head())
print(df.shape)
print(df.columns)

"""Now it is time to preprocessing:"""

import pandas as pd

df = pd.read_csv("/content/sample_data/train.csv")

print(df.columns.tolist())

from sklearn.preprocessing import LabelEncoder

df.drop("Loan_ID", axis=1, inplace=True)
label_cols = [
    'Gender',
    'Married',
    'Education',
    'Self_Employed',
    'Property_Area',
    'Loan_Status'

]
for col in label_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
df["Dependents"] = df["Dependents"].replace("3+", 3)
df["Dependents"] = pd.to_numeric(df["Dependents"])

df.fillna(df.median(numeric_only=True), inplace=True)
print(df.isnull().sum())

"""We are going for spliting our model to Train/Test part"""

from sklearn.model_selection import train_test_split

x = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y

)

"""It is time to create Missing Values for our dataset:

"""

import numpy as np
def inject_missing_values(data, percentage):
    corrupted = data.copy()
    total_values = corrupted.size
    n_missing = int(total_values * percentage)
    rows = np.random.randint(
        0,
        corrupted.shape[0],
        n_missing
    )
    cols = np.random.randint(
        0,
        corrupted.shape[1],
        n_missing
    )
    corrupted.values[rows, cols] = np.nan

    return corrupted

"""For Example we can see:"""

X_missing_10 = inject_missing_values(
    X_train,
    0.10
)

print(X_missing_10.isnull().sum())

"""Let's start Imputation for our dataset:"""

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
X_missing_10 = pd.DataFrame(
    imputer.fit_transform(X_missing_10),
    columns=X_train.columns
)

"""STEP 6 : Let's talk about Label Noise Function"""

def inject_label_noise(y, percentage):
    y_noisy = y.copy()
    n_flip = int(len(y)* percentage)
    flip_idx = np.random.choice(
        len(y),
        n_flip,
        replace=False
    )
    y_noisy.iloc[flip_idx] = 1 - y_noisy.iloc[flip_idx]
    return y_noisy

"""For example:"""

y_noise_20 = inject_label_noise(
    y_train,
    0.20
)

"""Let's talk about our Models:

"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
models = {
    "Logistic Regression":
        LogisticRegression(max_iter=2000),
    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),
    "XGBoost":
        XGBClassifier(
            random_state=42,
            eval_metric="logloss",

        )

}

"""Let's implement our Evaluation Function"""

from sklearn.metrics import (

    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)
def evaluate_model(model,
                   X_train,
                   y_train,
                   X_test,
                   y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    return {
        "accuracy":
            accuracy_score(y_test, pred),
        "Precision":
            precision_score(y_test, pred),
        "Recall":
            recall_score(y_test, pred),
        "F1":
            f1_score(y_test, pred)
    }

"""Now we are trying to Run Experiments:"""

results = []
corruption_levels = [
    0,
    0.05,
    0.10,
    0.20,
    0.30
]
for level in corruption_levels:
    X_corrupt = inject_missing_values(
        X_train,
        level
    )
    imputer = SimpleImputer(
        strategy="median"
    )

    X_corrupt = pd.DataFrame(
        imputer.fit_transform(X_corrupt),
        columns=X_train.columns
    )
    for name, model in models.items():
        metrics = evaluate_model(
            model,
            X_corrupt,
            y_train,
            X_test,
            y_test
        )
        metrics["Model"] = name
        metrics["Missing"] = level
        results.append(metrics)

"""Let's save the Results:"""

import os
import pandas as pd
os.makedirs("results", exist_ok=True)
results_df = pd.DataFrame(results)
results_df.to_csv(
    "results/missing_results.csv",
    index=False
)
print(results_df.head())

"""For a better understanding,we will try to drow a graphs"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.lineplot(

    data=results_df,
    x="Missing",
    y="accuracy",
    hue="Model",
    marker="o"
)
plt.title("Effect of Missing Values on Accuracy")
plt.xlabel("Missing Values Percentage")
plt.ylabel("Accuracy")

plt.show()

"""We Repeat for Label Noise:"""

import numpy as np
def inject_label_noise(y, percentage):
  y_noisy = y.copy()
  n_flip = int(len(y)* percentage)
  flip_idx = np.random.choice(
      len(y),
      n_flip,
      replace=False

  )
  y_noisy.iloc[flip_idx] = 1 - y_noisy.iloc[flip_idx]
  return y_noisy

y_noise_10 = inject_label_noise(y_train, 0.10)
print(y_train.head())
print(y_noise_10.head())

"""Instead of:

inject_missing_values()
"""

import pandas as pd
Label_noise_results_df = pd.DataFrame(results)

Label_noise_results_df.to_csv(
    "Label_noise_results.csv",
    index=False
)
print(Label_noise_results_df.head())